baseURL = "https://pinktalk.doowonee.com"

languageCode = "ko"
defaultContentLanguage = "ko"

[[params.css_list]]
link = "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css"
[[params.css_list]]
link = "https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.15.0/css/mdb.min.css"

[[params.js_list]]
link = "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
[[params.js_list]]
link = "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"
[[params.js_list]]
link = "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"
[[params.js_list]]
link = "https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.15.0/js/mdb.min.js"
[[params.js_list]]
link = "app.js"

[languages.ko]
title = "핑크톡"

[languages.ko.params]
    copyright = "두원이"
    
[languages.en]
title = "PinkTalk"
[languages.en.params]
    copyright = "Doowonee"